export type GhanaRegionDirectory = {
  region: string;
  districts: string[];
  constituencies: string[];
};

export const GHANA_ADMIN_DATA: GhanaRegionDirectory[] = [
  {
    region: "Ahafo",
    districts: [
      "Asunafo North",
      "Asunafo South",
      "Asutifi North",
      "Asutifi South",
      "Tano North",
      "Tano South",
    ],
    constituencies: [
      "Asunafo North",
      "Asutifi North",
      "Asutifi South",
      "Tano North",
    ],
  },
  {
    region: "Ashanti",
    districts: [
      "Adansi Asokwa",
      "Adansi North",
      "Adansi South",
      "Afigya-Kwabre North",
      "Afigya-Kwabre South",
      "Ahafo-Ano North",
      "Ahafo-Ano South East",
      "Ahafo-Ano South West",
      "Akrofuom",
      "Amansie Central",
      "Amansie South",
      "Amansie West",
      "Asante-Akim Central",
      "Asante-Akim North",
      "Asante-Akim South",
      "Asokore-Mampong",
      "Asokwa",
      "Atwima-Kwanwoma",
      "Atwima-Mponua",
      "Atwima-Nwabiagya",
      "Atwima-Nwabiagya North",
      "Bekwai",
      "Bosome Freho",
      "Bosomtwe",
      "Ejisu",
      "Ejura/Sekyedumase",
      "Juaben",
      "Kumasi",
      "Kwabre East",
      "Kwadaso",
      "Mampong",
      "Obuasi",
      "Obuasi East",
      "Offinso",
      "Offinso North",
      "Oforikrom",
      "Old Tafo",
      "Sekyere Afram Plains",
      "Sekyere Central",
      "Sekyere East",
      "Sekyere Kumawu",
      "Sekyere South",
      "Suame",
    ],
    constituencies: [
      "Manhyia South",
      "Oforikrom",
      "Bantama",
      "Bosomtwe",
      "Ejisu",
    ],
  },
  {
    region: "Bono",
    districts: [
      "Banda",
      "Berekum East",
      "Berekum West",
      "Dormaa Central",
      "Dormaa East",
      "Dormaa West",
      "Jaman North",
      "Jaman South",
      "Sunyani",
      "Sunyani West",
      "Tain",
      "Wenchi",
    ],
    constituencies: [
      "Sunyani East",
      "Sunyani West",
      "Berekum East",
      "Dormaa Central",
      "Wenchi",
    ],
  },
  {
    region: "Bono East",
    districts: [
      "Atebubu-Amantin",
      "Kintampo North",
      "Kintampo South",
      "Nkoranza North",
      "Nkoranza South",
      "Pru East",
      "Pru West",
      "Sene East",
      "Sene West",
      "Techiman",
      "Techiman North",
    ],
    constituencies: [
      "Techiman South",
      "Techiman North",
      "Atebubu-Amantin",
      "Kintampo North",
    ],
  },
  {
    region: "Central",
    districts: [
      "Abura/Asebu/Kwamankese",
      "Agona East",
      "Agona West",
      "Ajumako/Enyan/Essiam",
      "Asikuma Odoben Brakwa",
      "Assin Central",
      "Assin North",
      "Assin South",
      "Awutu Senya East",
      "Awutu Senya West",
      "Cape Coast",
      "Effutu",
      "Ekumfi",
      "Gomoa Central",
      "Gomoa East",
      "Gomoa West",
      "Komenda/Edina/Eguafo/Abirem",
      "Mfantsiman",
      "Twifo Atti Morkwa",
      "Twifo/Hemang/Lower Denkyira",
      "Upper Denkyira East",
      "Upper Denkyira West",
    ],
    constituencies: [
      "Cape Coast North",
      "Cape Coast South",
      "Effutu",
      "Assin Central",
      "Mfantseman",
    ],
  },
  {
    region: "Eastern",
    districts: [
      "Abuakwa North",
      "Abuakwa South",
      "Achiase",
      "Akuapim North",
      "Akuapim South",
      "Akyemansa",
      "Asene Manso Akroso",
      "Asuogyaman",
      "Atiwa East",
      "Atiwa West",
      "Ayensuano",
      "Birim Central",
      "Birim North",
      "Birim South",
      "Denkyembour",
      "Fanteakwa North",
      "Fanteakwa South",
      "Kwaebibirem",
      "Kwahu Afram Plains North",
      "Kwahu Afram Plains South",
      "Kwahu East",
      "Kwahu South",
      "Kwahu West",
      "Lower Manya Krobo",
      "New Juaben North",
      "New Juaben South",
      "Nsawam Adoagyire",
      "Okere",
      "Suhum",
      "Upper Manya Krobo",
      "Upper West Akim",
      "West Akim",
      "Yilo-Krobo",
    ],
    constituencies: [
      "New Juaben South",
      "Abuakwa South",
      "Abuakwa North",
      "Akuapem North",
      "Suhum",
    ],
  },
  {
    region: "Greater Accra",
    districts: [
      "Ablekuma Central",
      "Ablekuma North",
      "Ablekuma West",
      "Accra",
      "Ada East",
      "Ada West",
      "Adenta",
      "Ashaiman",
      "Ayawaso Central",
      "Ayawaso East",
      "Ayawaso North",
      "Ayawaso West",
      "Ga Central",
      "Ga East",
      "Ga North",
      "Ga South",
      "Ga West",
      "Korle-Klottey",
      "Kpone-Katamanso",
      "Krowor",
      "La-Dade-Kotopon",
      "La-Nkwantanang-Madina",
      "Ledzokuku",
      "Ningo-Prampram",
      "Okaikwei North",
      "Shai-Osudoku",
      "Tema Metropolitan",
      "Tema West",
      "Weija Gbawe",
    ],
    constituencies: [
      "Ayawaso West Wuogon",
      "Madina",
      "Okaikwei South",
      "Ningo-Prampram",
      "Tema Central",
    ],
  },
  {
    region: "Northern",
    districts: [
      "Gushegu Municipal",
      "Karaga",
      "Kpandai",
      "Kumbungu",
      "Mion",
      "Nanton",
      "Nanumba North Municipal",
      "Nanumba South",
      "Saboba",
      "Sagnarigu Municipal",
      "Savelugu Municipal",
      "Tamale Metropolitan",
      "Tatale Sanguli",
      "Tolon",
      "Yendi Municipal",
      "Zabzugu",
    ],
    constituencies: [
      "Tamale North",
      "Tamale South",
      "Yendi",
      "Savelugu",
      "Tolon",
    ],
  },
  {
    region: "North East",
    districts: [
      "Bunkpurugu Nyankpanduri",
      "Chereponi",
      "East Mamprusi",
      "Mamprugu Moagduri",
      "West Mamprusi",
      "Yunyoo-Nasuan",
    ],
    constituencies: [
      "Bunkpurugu",
      "Chereponi",
      "Nalerigu/Gambaga",
      "Walewale",
    ],
  },
  {
    region: "Oti",
    districts: [
      "Biakoye",
      "Jasikan",
      "Kadjebi",
      "Krachi East",
      "Krachi Nchumuru",
      "Krachi West",
      "Nkwanta North",
      "Nkwanta South",
    ],
    constituencies: ["Buem", "Guan", "Krachi East", "Krachi Nchumuru"],
  },
  {
    region: "Savannah",
    districts: [
      "Bole",
      "Central Gonja",
      "East Gonja Municipal",
      "North East Gonja",
      "North Gonja",
      "Sawla-Tuna-Kalba",
      "West Gonja",
    ],
    constituencies: [
      "Daboya-Mankarigu",
      "Bole-Bamboi",
      "Damongo",
      "Salaga South",
    ],
  },
  {
    region: "Upper East",
    districts: [
      "Bawku Municipal",
      "Bawku West",
      "Binduri",
      "Bolgatanga East",
      "Bolgatanga Municipal",
      "Bongo",
      "Builsa North Municipal",
      "Builsa South",
      "Garu",
      "Kassena-Nankana Municipal",
      "Kassena-Nankana West",
      "Nabdam",
      "Pusiga",
      "Talensi",
      "Tempane",
    ],
    constituencies: [
      "Bolgatanga Central",
      "Bawku Central",
      "Navrongo Central",
      "Zebilla",
    ],
  },
  {
    region: "Upper West",
    districts: [
      "Daffiama Bussie Issa",
      "Jirapa Municipal",
      "Lambussie Karni",
      "Lawra Municipal",
      "Nadowli-Kaleo",
      "Nandom Municipal",
      "Sissala East Municipal",
      "Sissala West",
      "Wa East",
      "Wa Municipal",
      "Wa West",
    ],
    constituencies: ["Wa Central", "Nadowli-Kaleo", "Lawra", "Sissala East"],
  },
  {
    region: "Volta",
    districts: [
      "Adaklu District",
      "Afadzato South",
      "Agotime Ziope",
      "Akatsi North",
      "Akatsi South",
      "Anloga",
      "Central Tongu",
      "Ho Municipal",
      "Ho West",
      "Hohoe Municipal",
      "Keta Municipal",
      "Ketu North Municipal",
      "Ketu South Municipal",
      "Kpando Municipal",
      "North Dayi",
      "North Tongu",
      "South Dayi",
      "South Tongu",
    ],
    constituencies: ["Ho Central", "Keta", "Ketu South", "Anlo", "South Dayi"],
  },
  {
    region: "Western",
    districts: [
      "Ahanta West",
      "Amenfi Central",
      "Amenfi West",
      "Effia Kwesimintsim Municipal",
      "Ellembelle",
      "Jomoro",
      "Mpohor",
      "Nzema East Municipal",
      "Prestea-Huni Valley Municipal",
      "Sekondi Takoradi Metropolitan",
      "Shama",
      "Tarkwa-Nsuaem Municipal",
      "Wassa Amenfi East",
      "Wassa East",
    ],
    constituencies: ["Sekondi", "Takoradi", "Effia", "Tarkwa-Nsuaem", "Jomoro"],
  },
  {
    region: "Western North",
    districts: [
      "Aowin",
      "Bia East",
      "Bia West",
      "Bibiani Anhwiaso Bekwai",
      "Bodi",
      "Juaboso",
      "Sefwi Akontombra",
      "Sefwi-Wiawso",
      "Suaman",
    ],
    constituencies: [
      "Sefwi-Wiawso",
      "Bibiani-Anhwiaso-Bekwai",
      "Suaman",
      "Bodi",
    ],
  },
];

export const GHANA_REGIONS = GHANA_ADMIN_DATA.map((entry) => entry.region);

export function getDistrictsForRegion(region: string) {
  return (
    GHANA_ADMIN_DATA.find((entry) => entry.region === region)?.districts ?? []
  );
}

export function getConstituenciesForRegion(region: string) {
  return (
    GHANA_ADMIN_DATA.find((entry) => entry.region === region)
      ?.constituencies ?? []
  );
}

export function getAllDistrictOptions() {
  return GHANA_ADMIN_DATA.flatMap((entry) =>
    entry.districts.map((district) => ({
      district,
      region: entry.region,
    })),
  );
}
